# docker-compose.yml
version: '3.3'
services:

  # #Nginx Service
  # webserver:
  #   image: nginx:alpine
  #   container_name: webserver
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./webserverfiles/nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./webserverfiles/nginx-logs/:/tmp/logs/
  #     - /etc/letsencrypt/:/etc/letsencrypt/
  #   depends_on:
  #     - webapp
  #     - thedatabase
  #   networks:
  #     - webapp-network

  thedatabase:
    image: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpass
    networks:
      - webapp-network
    # ports:
    #   - '5432:5432'

  webapp:
    build:
      context: ./web
    volumes:
      - ./web:/web
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: devpass
      DB_HOST: thedatabase
      DB_PORT: 5432
      DB_POOL: 20
      APP_DOMAIN: "https://dev.xaurius.com"
      LETTER_OPENER_YN: "no"
      ADMIN_ROOT_ID: 1
      EMAIL: info@xaurius.com
      EMAIL_PASSWORD: XauriusGold20
      EMAIL_DOMAIN: xaurius.com
      EMAIL_SMTP: smtpout.secureserver.net
      EMAIL_SMTP_PORT: 587
    ports:
      - "3000:3000"
    depends_on:
      - thedatabase
    networks:
      - webapp-network

volumes:
  database:
  web:
  webserverfiles:

networks:
  webapp-network:
    driver: bridge
